# Generated by Django 4.1.5 on 2023-01-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mma", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mma",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="mma",
            name="nickname",
            field=models.CharField(max_length=50),
        ),
    ]
